---
title: "Boletim Diário - COVID19"
author: "Mário Olímpio de Menezes"
date: "19/04/2020"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    fig_height: 6
    fig_width: 8
    toc: yes
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, knitr.kable.NA = '')
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(forcats)
library(ggpubr)
library(readxl)
library(knitr)
library(stringi)
library(RColorBrewer)
library(ggthemes)
library(plotly)
library(rvest)
library(data.table)
library(scales)
library(kableExtra)
library(DT)
library(plotly)
library(formattable)
library(gganimate)
```


```{r}
theme_set(theme_clean())
```


# Resumo dos Dados Mundiais da COVID-19 {#ResumoMundo}

## Dados obtidos da John Hopkins University

```{r}
jhucovid19 <- read_csv("./data/jhucovid19_last.csv")
```


```{r}
Fonte = "Fonte: CSSE at Johns Hopkins University"
```

```{r}
ultimadata <- max(jhucovid19$DateRep)
```


### Total de Casos pelos dados da John Hopkins University (JHU): `r format(ultimadata, '%d-%m-%Y')` {#JHUtotal}


```{r}
 jhucovid19 %>% 
  group_by(Country) %>% 
  summarise(CasosPais = last(ConfirmedCases), MortosPais = last(Deaths), RecuperadosPais = last(Recovered)) %>% 
  summarise(`Casos Confirmados` = sum(CasosPais), Mortos = sum(MortosPais), Recuperados = sum(RecuperadosPais)) %>% kable()
```


```{r}
jhucovid19 <- group_by(jhucovid19, Country) %>% 
  arrange(DateRep) %>%
  mutate(NewDeaths = Deaths - lag(Deaths), 
         NewCases = ConfirmedCases - lag(ConfirmedCases),
         NewCases = if_else(is.na(NewCases), 0, if_else(NewCases < 0, 0, NewCases)),
         NewDeaths = if_else(is.na(NewDeaths), 0, if_else(NewDeaths < 0, 0, NewDeaths))
         ) %>%
  ungroup()
```


```{r}
CasosRemovidos <- filter(jhucovid19, is.na(Continent))
numNAsCont <- CasosRemovidos %>% count() %>% as.numeric()
numCasosSemCont <- CasosRemovidos %>% group_by(Country) %>% summarise(Casos = sum(ConfirmedCases)) %>% summarise(CasosTot = sum(Casos)) %>% select(CasosTot) %>% as.numeric()
```


```{r}
jhucovid19 <- filter(jhucovid19, !is.na(Continent))
```

```{r}
nma = 5
```


```{r}
jhucovid19 %<>% 
  group_by(Country) %>% 
  filter(ConfirmedCases >= 1) %>% 
  arrange(DateRep) %>%
  mutate(ProgRateDeaths = (Deaths - lag(Deaths))/lag(Deaths), 
         ProgRateCases = (ConfirmedCases - lag(ConfirmedCases))/lag(ConfirmedCases),
         ProgRateDeaths = ProgRateDeaths + 1,
         ProgRateCases = ProgRateCases + 1
         ) 
setDT(jhucovid19)
setkey(jhucovid19,DateRep,Country)
jhucovid19[,NewCasesMA:=as.numeric(frollmean(NewCases,n=nma, align='right',hasNA=TRUE)), by=Country]
jhucovid19[,ProgRateCasesMA:=as.numeric(frollmean(ProgRateCases,n=nma, align='right',hasNA=TRUE)), by=Country]
jhucovid19 <- as_tibble(jhucovid19)

```

```{r}
# populacao mundial - https://population.un.org/wpp/Download/Standard/CSV/
# filtrei apenas 2019 e 2020, peguei os últimos valores de cada ano por pais (Location)
# mantive valores por sexo e também densidade populacional
worldpop <- read_csv("./data/populacao20192020.csv")
```


```{r}
worldpop <- worldpop %>% filter(Year == 2020)
```

```{r}
str(jhucovid19, give.attr = FALSE)
```

```{r}
str(worldpop, give.attr = FALSE)
```

```{r}
# juntando dados da população de cada país
jhucovid19 <- left_join(jhucovid19,select(worldpop,-Country,-Continent), by = "Code")
```


